SYMBOL: AAPL
EXECUTION_TIMEFRAME: 1min
EXECUTION_FREQ: 1min
SIGNALS_TIMEFRAME: daily

BACKTESTING_START_DATE: '2020-01-01'
BACKTESTING_END_DATE: '2025-10-01'
CONVERT_TO_NY_TIMEZONE: false
ALLOW_SHORT: true
FEES: 0
INIT_BALANCE: 100000
POSITION_SIZE: 4
POSITION_SIZE_TYPE: amount
SLIPPAGE: 0
SMA_FAST: 20
SMA_SLOW: 50

OPTIMIZATION_STEP: 10
OPTIMIZATION_START: 20
OPTIMIZATION_END: 60
